### ISSUE TITLE
Error creating users table on MySQL 5.5

### ISSUE THREAD

**Issue by GaneshKandu** [mudmin/UserSpice5#12]
Hi,

I am getting an error while install of UserSpice 5.1.9 

PHP Version : 5.6.40
MySQL Version : 5.5.62
OS : CentOS

```
Error performing query:
CREATE TABLE `users` ( `id` int(11) NOT NULL, `permissions` tinyint(1) NOT NULL, `email` varchar(155) NOT NULL, `email_new` varchar(155) DEFAULT NULL, `username` varchar(255) NOT NULL, `password` varchar(255) DEFAULT NULL, `pin` varchar(255) DEFAULT NULL, `fname` varchar(255) NOT NULL, `lname` varchar(255) NOT NULL, `language` varchar(255) DEFAULT '''en-US''', `email_verified` tinyint(1) NOT NULL DEFAULT 0, `vericode` varchar(15) DEFAULT NULL, `vericode_expiry` datetime DEFAULT NULL, `oauth_provider` varchar(255) DEFAULT NULL, `oauth_uid` varchar(255) DEFAULT NULL, `gpluslink` varchar(255) DEFAULT NULL, `account_owner` tinyint(4) NOT NULL DEFAULT 0, `account_id` int(11) NOT NULL DEFAULT 0, `account_mgr` int(11) NOT NULL DEFAULT 0, `fb_uid` varchar(255) DEFAULT NULL, `picture` varchar(255) DEFAULT NULL, `protected` tinyint(1) NOT NULL DEFAULT 0, `msg_exempt` tinyint(1) NOT NULL DEFAULT 0, `dev_user` tinyint(1) NOT NULL DEFAULT 0, `msg_notification` tinyint(1) NOT NULL DEFAULT 1, `cloak_allowed` tinyint(1) NOT NULL DEFAULT 0, `oauth_tos_accepted` tinyint(1) DEFAULT NULL, `un_changed` tinyint(1) NOT NULL DEFAULT 0, `force_pr` tinyint(1) NOT NULL DEFAULT 0, `logins` int(11) UNSIGNED NOT NULL DEFAULT 0, `last_login` datetime DEFAULT NULL, `join_date` datetime NOT NULL DEFAULT current_timestamp(), `modified` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
Error performing query:
INSERT INTO `users` (`id`, `permissions`, `email`, `email_new`, `username`, `password`, `pin`, `fname`, `lname`, `language`, `email_verified`, `vericode`, `vericode_expiry`, `oauth_provider`, `oauth_uid`, `gpluslink`, `account_owner`, `account_id`, `account_mgr`, `fb_uid`, `picture`, `protected`, `msg_exempt`, `dev_user`, `msg_notification`, `cloak_allowed`, `oauth_tos_accepted`, `un_changed`, `force_pr`, `logins`, `last_login`, `join_date`, `modified`) VALUES (1, 1, 'userspicephp@userspice.com', NULL, 'admin', '$2y$12$1v06jm2KMOXuuo3qP7erTuTIJFOnzhpds1Moa8BadnUUeX0RV3ex.', NULL, 'The', 'Admin', 'en-US', 1, 'nlPsJDtyeqFWsS', NULL, '', '', '', 0, 0, 0, '', '', 1, 1, 0, 1, 0, NULL, 0, 0, 0, '2016-01-01 00:00:00', '2016-01-01 00:00:00', '2016-01-01 00:00:00');
Error performing query:
ALTER TABLE `logs_exempt` ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `logs_exempt_type` (`name`);
Error performing query:
ALTER TABLE `users` ADD PRIMARY KEY (`id`), ADD KEY `EMAIL` (`email`) USING BTREE;
Error performing query:
ALTER TABLE `logs_exempt` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
Error performing query:
ALTER TABLE `users` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3; 
```

> entries are removed for screenshot

![image](https://user-images.githubusercontent.com/12833130/97776960-93932000-1b92-11eb-8915-4053eaed0fef.png)

**Comment by brandinarsenault** [comment]
I cannot reproduce this issue on the latest version of MariaDB. Please run these queries directly in phpMyAdmin on the database created to see if you can provide the errors that occured. 

At the very least, you need to use a more up-to-date PHP version. UserSpices requires PHP 7 at a minimum.

**Comment by GaneshKandu** [comment]
Hi,

I am getting same error when i run queries directly in phpMyAdmin on the database i created.

Is minimum required php version and MySQL/MariaDB version changed ?

**Comment by brandinarsenault** [comment]
What is the error though? You're not providing any information. Just providing the "error performing query" doesn't guide us to any issue.

**Comment by GaneshKandu** [comment]
> What is the error though? You're not providing any information. Just providing the "error performing query" doesn't guide us to any issue.

Did you tried install on MySQL 5.5 ?

> UserSpices requires PHP 7 at a minimum.

I think UserSpice requires ~MySQL 5.6 at a minimum

**Comment by GaneshKandu** [comment]
Getting same issue on 5.2.0 while install on MySQL 5.5
working on 5.6, 5.7 and 8.0

you need to change MySQL query or need to change minimun supported version for UserSpice.

**Comment by brandinarsenault** [comment]
The issue is we're not exactly certain what in the query is causing the issue since the error message is so generic.

**Comment by brandinarsenault** [comment]
I've identified the error code being related to the `CURRENT_TIMESTAMP()` default set on the `join_date` and `modified` columns. We are reviewing our minimum requirements to make them more defined. At this time, MySQL 5.6 and above should install without issue and would be my own recommendation at minimum. I've opened a Bug ticket instead for this, as we don't really use GitHub Issues:
