### ISSUE TITLE
Secret 2FA key stored in cleartext in database

### ISSUE THREAD

**Issue by iMelsom** [mudmin/UserSpice5#18]
When generating the QRcode for the Twofactor app the secret key for manually entering is stored in clear text. This means that anyone getting access to the database may add any users with two factor active to their two factor app.

I am unsure where the encryption of this code should be done som I'm reporting it here as well as to the maker of the twofactor addon also: https://github.com/bangingheads/UserSpiceTwoFactor/issues/1

**Comment by brandinarsenault** [comment]
2FA is not supported in core code. Please make a request in the addon only.
