### ISSUE TITLE
Missing Language of Admin Menu 

### ISSUE THREAD

**Issue by supersavio** [mudmin/UserSpice5#22]
Hello,
in version 5.4 the label in the admin menu is missing after update languange. When change from EN to IT, the label get lost

**Comment by supersavio** [comment]
> Can you provide some more information, screenshots, reproduction steps? There is little data to work off here. What exactly is missing?

Inside the file it-IT.php ( ./users/lang/it-IT.php ) missing this code,  i have translate the labels missing:



```
//Backend Translations for UserSpice
$lang = array_merge($lang,array(
    "BE_DASH"    			=> "Dashboard",
    "BE_SETTINGS"           => "Impostazioni",
    "BE_GEN"				=> "Generali",
    "BE_REG"				=> "Registrazione",
    "BE_CUS"				=> "Personalizzazione",
    "BE_DASH_ACC"			=> "Accesso alla Dashboard",
    "BE_TOOLS"				=> "Strumenti",
    "BE_BACKUP"				=> "Backup",
    "BE_UPDATE"				=> "Aggiornamento",
    "BE_CRON"				=> "Cron Jobs",
    "BE_IP"				  	=> "IP Manager",
    ));
```

after this update, it's all ok

**Comment by Brandin** [comment]
Ticketed https://bugs.userspice.com/issue/1465/
