### ISSUE TITLE
Install Database port not used.

### ISSUE THREAD

**Issue by steves2j** [mudmin/UserSpice5#24]
On installing Userspice there is a text field in step2.php that is used for a port to the db. This is not used in the connection to the database and causes the install to fail if trying to connect to a mysql install that is not on port 3306.

To work around this I had to put the port number in the url to the database I.E. 127.0.0.1:13306 to get this to work.

This either needs to be detailed in the install instructions and or the port field removed to avoid confusion.

**Comment by mudmin** [comment]
I haven't seen that issue.  Can you tell me what kind of server you're on?  

It should write like this...
$GLOBALS['config'] = array(
	'mysql'      => array(
'host'         => '127.0.0.1; port=3306',
'username'     => 'root',

**Comment by steves2j** [comment]
I'm on a Debian linux distro connecting to a docker image of mysql.

**Comment by mudmin** [comment]
I'm guessing that's a docker issue. I use it on nonstandard ports all the time.
