### ISSUE TITLE
Japanese Language Support - UsersSpice 5.6.7

### ISSUE THREAD

**Issue by bestwmm** [mudmin/UserSpice5#31]
Attached are files needed for Japanese language support in UserSpice 5.6.7.  Unzip to your documents folder and it will create users/lang/ja-JP.php and users/lang/flags/ja-JP.png.
[Japanese.zip](https://github.com/mudmin/UserSpice5/files/14462305/Japanese.zip)

**Comment by mudmin** [comment]
Thank you!
