### ISSUE TITLE
UserSpice 5.6.7 extraneous </body> tag in footer.php

### ISSUE THREAD

**Issue by bestwmm** [mudmin/UserSpice5#32]
usersc/templates/bs5/footer.php contains a </body> tag, but so does users/includes/html_footer.php, which is included immediately after that.

The extra tag in footer.php should be removed.

**Comment by mudmin** [comment]
I'm aware of this but it has to be fixed in (nearly) every single template, so since nothing is broken, I'm doing it little by little

**Comment by mudmin** [comment]
I was wrong. This can be fixed in html_footer. Thanks for pointing that out.
