### ISSUE TITLE
UserSpice 5.6.7 w3c validator warnings

### ISSUE THREAD

**Issue by bestwmm** [mudmin/UserSpice5#33]
The w3c validator service reports many warnings for the following:

- Unnecessary "type=text/javascript" in <script> tags.

- Unnecessary "/" to close <img>, <br>, and <meta> tags.  There are additional cases in the code that initializes the database, and there are two cases in the live us_menus table.  I forgot now - there is maybe a case with one or more <input> tags.

- Missing alt property for some <img> tags.  I found two cases searching for logo.png, and there are two cases each in the database initialization code and the live us_menus table.  I set mine to "site logo".  (Please don't set it to UserSpice because then developers have to change it anyway!)

- users/includes/template/prep.php includes header.php (which adds <body>), navigation.php, and system_message_header.php. The latter two contain <script> elements, which are only allod in the <head>, but by now we're in the body.  DH: Where should these go? 
 I put my in header.php for now pending feedback.
 
 None of these are errors, but it is nice to get a clean report out of this validation service.  There are a few other validation issues related to Menu.php that I'll report separately.

**Comment by mudmin** [comment]
I'm moving this to our bug reports over on bugs.userspice.com
